### PR TITLE
Update basis set

### PR DESCRIPTION
**Pull request by ndaelman-hu**
Applies the updated `BasisSet` metainfo introduced in https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/merge_requests/1264.
Heavily extends the LAPW basis sets in _exciting_, fleur, wien2k (but not elk).

### CODE REVIEW

**Comment by JosePizarro3** [comment]
> Everything should be updated before merging. Electronic parsers are already done, normalization mostly so. I'll trace the errors and tackle this.

`utils/utils.py` should be also updated in line 129 (when extracting the `run/method/basis_set` for the `workflow2.method`), as well as its corresponding metainfo in workflow. I wonder whether it should be moved then to the `WorkflowNormalizer` anyways, similar to the dos, band_structure, and band_gap. Let me know.

**Comment by ndaelman-hu** [comment]
Extended the change to `GWMethod`. Thank you for brining it up, though pls note that even without these corrections, it passes the tests. I recommend that you consider adding more tests in this regime, diminishing the burden on the original author to follow up.

Regarding the placement, I quite neutral here, though your suggestion sounds good. Since this is more of a lay-out consideration, I consider it outside the scope of this PR. I suggest looking into it after @ladinesa has consolidated his workflow changes.

**Comment by ndaelman-hu** [comment]
Additional note: `basis_set` and `electrons_representation` are both repeated sections in `run.method`, but not in `gw_method`. Should I change this?

**Comment by JosePizarro3** [comment]
> though pls note that even without these corrections, it passes the tests. I recommend that you consider adding more tests in this regime, diminishing the burden on the original author to follow up.

Yes, it is because the GW workflow archive it is not passed in the tests, but rather the main first one, i.e., the DFT archive. Maybe @ladinesa can tell us if it is possible to test specific child archives in the testing of each parser? But I remember we cannot.

> Additional note: basis_set and electrons_representation are both repeated sections in run.method, but not in gw_method. Should I change this?

Why this section is repeated? For me it is ok to keep it the same, so you can change that if you don't mind. Thanks!

**Pull request merged**
