### PR TITLE
Fix quantity types

### PR DESCRIPTION
**Pull request by ladinesa**
Fix wrong type and shape in metainfo quantities. @TLCFEM

### CODE REVIEW

**Review by JFRudzinski — APPROVED** [review]
This seems all fine to me. You may also want @ndaelman-hu to take a quick look in terms of some of the more specific things that you changed.

Question: Is there any case that one would use `np.dtype()` now? I vaguely remember in the past having to use this for some more complicated array structure, but I can't really remember or might be mistaken, or maybe something has changed.

**Comment by ladinesa** [comment]
> This seems all fine to me. You may also want @ndaelman-hu to take a quick look in terms of some of the more specific things that you changed.
> 
> Question: Is there any case that one would use `np.dtype()` now? I vaguely remember in the past having to use this for some more complicated array structure, but I can't really remember or might be mistaken, or maybe something has changed.

You can stil use np.dtype() and it would be equivalent to not using it, it is a matter of preference I guess but @TLCFEM may know more.

**Comment by ndaelman-hu** [comment]
@ladinesa Are there any quantities that you didn't feel sure about? Anything that you want me to check in particular?

**Comment by ladinesa** [comment]
> @ladinesa Are there any quantities that you didn't feel sure about? Anything that you want me to check in particular?

Nothing in particular. I did not make any changes in the schema, simply made sure that the assigned values are compatible with the defs.

**Pull request merged**
