### PR TITLE
Remove workflow schema from nomad

### PR DESCRIPTION
**Pull request by ladinesa**
Simulation workflow schema are moved to a plug in https://github.com/nomad-coe/nomad-schema-plugin-simulation-workflow. References to the old schema are removed.

### CODE REVIEW

**Comment by ladinesa** [comment]
@ndaelman-hu can I simply merge this? I would like to merge the nomad mr soonish. thanks

**Review by ndaelman-hu — COMMENTED** [review]
Pls double-check `./electronicparsers/charmm/metainfo/charmm.py`, line 1335: `class MolecularDynamics(simulation.workflow.MolecularDynamics):`.

A cursory search did not indicate any other occurrences.
I have the impression that you used `sed` to replace the pattern, but only applied it to `nomad.datamodel.metainfo.simulation.workflow`.
There's also the option to use `Rename Symbol` in VS, which tends to have a better coverage.

Overall, I like this change. It's much clearer and will help with migrating to base classes. Thx!

**Comment by ndaelman-hu** [comment]
@JosePizarro3 it's good that you know this migration happened.

**Comment by ladinesa** [comment]
> Pls double-check `./electronicparsers/charmm/metainfo/charmm.py`, line 1335: `class MolecularDynamics(simulation.workflow.MolecularDynamics):`.
> 
> A cursory search did not indicate any other occurrences. I have the impression that you used `sed` to replace the pattern, but only applied it to `nomad.datamodel.metainfo.simulation.workflow`. There's also the option to use `Rename Symbol` in VS, which tends to have a better coverage.
> 
> Overall, I like this change. It's much clearer and will help with migrating to base classes. Thx!

nice catch thanks

**Pull request merged**
