### PR TITLE
Add date_start and date_end for openmx parser + tests

### PR DESCRIPTION
**Pull request by jfrodlova**

### CODE REVIEW

**Comment by ondracka** [comment]
ping @ndaelman-hu @ladinesa 

Hi guys, @jfrodlova is my colleague, now working on some nomad improvements for a local Oasis. This one is just a simple parser enhancement, related to the topic having a time-based search field for when specific calculation was done (we are working also on the server-side changes, discussed at Discord https://discord.com/channels/1201445470485106719/1211709027365552220 but those are not ready yet). 

I did some preliminary review, but more feedback would be welcomed as always.

**Comment by ondracka** [comment]
I'll just merge this in a few days if there are no objections.

**Review by JosePizarro3 — APPROVED** [review]
Please, go ahead. Very nice! 👍🏻

**Comment by JosePizarro3** [comment]
I will also answer in the Discord thread, sorry, I am not following the oasis channel too much 🙂

**Comment by ondracka** [comment]
Thanks Jose

**Comment by ondracka** [comment]
@JosePizarro3 BTW the test failures are not our fault, right (we passed everything before)? This looks more like some out of sync with main nomad repo?

**Comment by JosePizarro3** [comment]
> @JosePizarro3 BTW the test failures are not our fault, right (we passed everything before)? This looks more like some out of sync with main nomad repo?

Yeah, I think so. Strange that now it is having some errors with it, probably it is related with the plugins transfer.

I would not worry too much I were you; just make sure that the testing passes locally by doing `python -m pytest -sv tests` (and pray that the FHIaims parser does not kill the memory of your computer during pytesting... 😆 )

**Pull request merged**
