### PR TITLE
Fix cp2k inp

### PR DESCRIPTION
**Pull request by ndaelman-hu**
Fix a loophole in the logic where CP2K tries to access an empty list of (restarted) input files.

Prompted by user Max Graml. Here's a screenshot of the failing logs:
Screenshot from 2024-12-16 18-04-25

### CODE REVIEW

**Review by ladinesa — APPROVED** [review]

**Comment by ndaelman-hu** [comment]
@ladinesa could we see to roll this out for Max/

**Comment by ladinesa** [comment]
> @ladinesa could we see to roll this out for Max/

i can create a release, but I am sure it will trigger some compatibility issues again in nomad... but I think it is perfect time to have issues since it is the holidays. are you sure you have all fixes in now in develop?

**Comment by ndaelman-hu** [comment]
> but I think it is perfect time to have issues since it is the holidays.

Let's wait for the new year then. I'll inform Max.

> are you sure you have all fixes in now in develop?

The other failed calculations had the same error.

**Comment by ladinesa** [comment]
please advise when I should make a release.

**Pull request merged**
