### PR TITLE
Updated DOS integrator

### PR DESCRIPTION
**Pull request by ndaelman-hu**
Update the parser tests to use the new and migrated DOS integrator, which is being merged in https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/merge_requests/963.

### CODE REVIEW

**Review by ladinesa — COMMENTED** [review]
I would completely remove the tests for the integrator here and put them in nomad tests/normalizing. We should test only parsed data here.

**Comment by ndaelman-hu** [comment]
I see, but the test is run over the `run` values, before any normalization is even performed.

**Comment by ndaelman-hu** [comment]
Btw, my pipeline on Gitlab seems to break when loading the electronic parser: https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/jobs/1935797

**Comment by ladinesa** [comment]
> normalization
You can access the these "run" values in the normalization. After all, these integrator function is now in normalizing so you should test it there.

**Comment by ladinesa** [comment]
> Btw, my pipeline on Gitlab seems to break when loading the electronic parser: https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/jobs/1935797

Can you please clarify this with @fekad, I think it is related with the merge I did with the new setup process.

**Comment by ndaelman-hu** [comment]
Okay, I'll migrate them. Still, this branch will have to be merged, just to remove the old code.

**Comment by ladinesa** [comment]
> Okay, I'll migrate them. Still, this branch will have to be merged, just to remove the old code.

yes please remove the tests then we will merge.

**Pull request closed without merging**
